site_name: SQLite Dokumentation
extra_css: [extra.css]
nav:
    - 'index.md'
    - SELECT: 'select.md'
    - WHERE: 'where.md'
    - WHERE 2: 'where2.md'
    - JOIN: 'join.md'
    - AGGREGATE: 'aggregate.md'
plugins:
    - search:
        lang: de
        
