site_name: SQLite Dokumentation
repo_url: https://github.com/Sulkar/sqlite-dokumentation/
theme:
    name: mkdocs
    custom_dir: custom_theme/
    highlightjs: true
    hljs_languages:
        - sql
extra_css: [extra.css]
plugins:
    - search:
        min_search_length: 2
        prebuild_index: python
nav:
    - SELECT: 'select.md'
    - WHERE: 'where.md'
    - ORDER: 'order.md'
    - LIMIT: 'limit.md'
    - JOIN: 'join.md'
    - AGGREGATE: 'aggregate.md'
    - UPDATE: 'update.md'
    - DELETE: 'delete.md'
    - INSERT: 'insert.md'
    - TABLE:
        - CREATE: 'create.md'
        - DROP: 'drop.md'
        - ALTER: 'alter.md'
   

        
